### PR TITLE
Improve og description

### PR DESCRIPTION
**Pull request by kiyov09**
These are changes intended to fix issue #158

### CODE REVIEW

**Comment by kiyov09** [comment]
Question:
Is there any reason for extracting the description from the content instead of having some kind of configuration for it?
For example: For authors, the description is defined in the `bio` prop of the author.

I think that we can give users more control over what they want the description to be if it's defined explicitly. For example, using [gray_matter](https://docs.rs/gray_matter/latest/gray_matter/) provides a way to define metadata inside the md file.

What do you think?

**Comment by kiyov09** [comment]
Also, I think we need to exclude the links from the description extraction. Taking your "bio" as an example, in the current implementation the description ends up containing the "Github" word (from your github link) but I don't think that makes sense in the description.

**Comment by Folyd** [comment]
The main reason why we extract the description from markdown is I hope to keep zine as simple as possible. The less property the better for the user. Maybe we can add an optional property to allow customizing the description?

```toml
[[article]]
summary = "article summary"
```

Also good to know the gray_matter crate, I had considered using the front matter to replace the issue's zine.toml, maybe it should add to the plan.

**Comment by kiyov09** [comment]
Roger that.

**Comment by Folyd** [comment]
> Also, I think we need to exclude the links from the description extraction. Taking your "bio" as an example, in the current implementation the description ends up containing the "Github" word (from your github link) but I don't think that makes sense in the description.

We can't exclude all links from the description, for example, Rust Search Extension in my bio is key info. I think the GitHub link in my bio is just a corner case, so we needn't put much attention to it.

**Pull request merged**
