### PR TITLE
Fix the styles of the issue card on mobile devices

### PR DESCRIPTION
**Pull request by kiyov09**
This PR is a fix for issue #160 

Below is a screenshot comparing new changes (left) to the live version of the rust magazine (right)

Screenshot 2023-02-08 at 8 40 55

### CODE REVIEW

**Review by Folyd — APPROVED** [review]
Cool, thanks for working on this. ❤️

**Comment by Folyd** [comment]
BTW, do you mind fixing the author page? See the `templates/_article_ref.jinja` file.
image

**Comment by kiyov09** [comment]
Sure. Should I open another issue?

**Comment by Folyd** [comment]
Oh yes, I merged this PR already. 😄

**Comment by kiyov09** [comment]
Np. I'll open a new issue and start working on it.

**Pull request merged**
