### PR TITLE
Refactor new commands

### PR DESCRIPTION
**Pull request by Bas-Man**
- Refactor: how Site struct is created
- Feat: Add a way to create a new issue by chaining
- Commit to Support new Article features
- Clippy and formating fixes
- Add tempdir crate for testing toml file read/write
- Refactor: Tests to use tempdir crate
- Re-import modules
- Create Site and default article
- Refactor: Move SiteBuilder to new.rs file
- Feature: Implement Display for Author
- Documentation for new code

This commit also removes the need for tera and time from the new.rs file.
the toml crate is used to write the zine.toml files instead. This means that changing the structs will ensure that zine files are written correctly.

### CODE REVIEW

**Comment by Bas-Man** [comment]
@Folyd I think this code is ready for a proper review.

I have some thoughts about providing the ability to have the slug be `/year/month/issue/`
What are you plans for the default slug to be? Currently its `{issue}-{issue_number}`

**Comment by Folyd** [comment]
We already support slugs like `/year/month/issue/`, simply set the slug to "2022/2" directly, and the URL will be rendered to "https://domain.tld/2022/2/article". 😄 

```toml
slug = "2022/2"
number = 2
title = "Issue 2"
```

**Comment by Bas-Man** [comment]
I am
Glad I stopped overwriting the slug value.

**Comment by Bas-Man** [comment]
I don't want to add more code to this pull-request has it is already very big. It is already difficult to check.
Once its approved I can move on to implementing the --new-article feature and clean up some of the code.

**Comment by Bas-Man** [comment]
This will be closed by #162

**Comment by Bas-Man** [comment]
Closing this pull request as it has been replaced by pr #177

**Pull request closed without merging**
