### PR TITLE
Fix copy_dir and add demo test

### PR DESCRIPTION
**Pull request by KernelErr**
Signed-off-by: KernelErr <me@lirui.tech>

### CODE REVIEW

**Comment by KernelErr** [comment]
Can you have a check on why it failed? @Folyd 

If you delete the generated folder `build` and use `zine build` to build again. It might fail.

image

**Comment by KernelErr** [comment]
After using `par_bridge`, copying files may be ahead of creating its directory. I tried to fix this.

https://github.com/zineland/zine/blob/54c4bebcb6048b36f286b05f083189718aee9a5e/src/helpers.rs#L135-L153

**Comment by KernelErr** [comment]
Now we don't create the directory if it's empty.

**Review by Folyd — APPROVED** [review]
LGTM. BTW, I add some comments.

**Pull request merged**
