### PR TITLE
add new article support

### PR DESCRIPTION
**Pull request by Bas-Man**
- Refactor: how Site struct is created
- Feat: Add a way to create a new issue by chaining
- Commit to Support new Article features
- Clippy and formating fixes
- Add tempdir crate for testing toml file read/write
- Refactor: Tests to use tempdir crate
- Re-import modules
- Create Site and default article
- Refactor: Move SiteBuilder to new.rs file
- Feature: Implement Display for Author
- Documentation for new code
- remove debug line
- cargo fmt command issued
- Clippy based fixes against master
- General Clippy fixes
- Clippy and formatting
- Fix: MetaArticle::default_pub_date()
- Fix: Added code to handle duplicate issue creation
- Add: Initial commit for new Article
- Comment and new function
- Add function write_markdown_tempate
- Feature: Add --article support

### CODE REVIEW

**Comment by Bas-Man** [comment]
This pull request will also close pr #162

**Comment by Bas-Man** [comment]
I think this is now complete and ready. It also contains the latest changes from master that were causing conflicts.

**Comment by Bas-Man** [comment]
I dont know where this pub_date error is coming from in the build. Things appear to be compiling correctly on my Mac.

**Comment by Bas-Man** [comment]
I am also getting this odd duplication. Does not appear to happen in master under `--release`

```sh
 ~/Documents/Development/rust/zine/target/release/zine serve


███████╗██╗███╗   ██╗███████╗
╚══███╔╝██║████╗  ██║██╔════╝
  ███╔╝ ██║██╔██╗ ██║█████╗
 ███╔╝  ██║██║╚██╗██║██╔══╝
███████╗██║██║ ╚████║███████╗
╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝


listening on http://127.0.0.1:3000


███████╗██╗███╗   ██╗███████╗
╚══███╔╝██║████╗  ██║██╔════╝
  ███╔╝ ██║██╔██╗ ██║█████╗
 ███╔╝  ██║██║╚██╗██║██╔══╝
███████╗██║██║ ╚████║███████╗
╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝


listening on http://127.0.0.1:3000
Build cost: 8ms
Watching...
```

**Comment by Bas-Man** [comment]
> I am also getting this odd duplication. Does not appear to happen in master under `--release`
> 
> ```shell
>  ~/Documents/Development/rust/zine/target/release/zine serve
> 
> 
> ███████╗██╗███╗   ██╗███████╗
> ╚══███╔╝██║████╗  ██║██╔════╝
>   ███╔╝ ██║██╔██╗ ██║█████╗
>  ███╔╝  ██║██║╚██╗██║██╔══╝
> ███████╗██║██║ ╚████║███████╗
> ╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝
> 
> 
> listening on http://127.0.0.1:3000
> 
> 
> ███████╗██╗███╗   ██╗███████╗
> ╚══███╔╝██║████╗  ██║██╔════╝
>   ███╔╝ ██║██╔██╗ ██║█████╗
>  ███╔╝  ██║██║╚██╗██║██╔══╝
> ███████╗██║██║ ╚████║███████╗
> ╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝
> 
> 
> listening on http://127.0.0.1:3000
> Build cost: 8ms
> Watching...
> ```
This comes from src/server.rs. There was an issue with my merging.

**Comment by Folyd** [comment]
> I dont know where this pub_date error is coming from in the build. Things appear to be compiling correctly on my Mac.

#178 try to fix it.

**Comment by Folyd** [comment]
> > I am also getting this odd duplication. Does not appear to happen in master under `--release`
> > ```shell
> >  ~/Documents/Development/rust/zine/target/release/zine serve
> > 
> > 
> > ███████╗██╗███╗   ██╗███████╗
> > ╚══███╔╝██║████╗  ██║██╔════╝
> >   ███╔╝ ██║██╔██╗ ██║█████╗
> >  ███╔╝  ██║██║╚██╗██║██╔══╝
> > ███████╗██║██║ ╚████║███████╗
> > ╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝
> > 
> > 
> > listening on http://127.0.0.1:3000
> > 
> > 
> > ███████╗██╗███╗   ██╗███████╗
> > ╚══███╔╝██║████╗  ██║██╔════╝
> >   ███╔╝ ██║██╔██╗ ██║█████╗
> >  ███╔╝  ██║██║╚██╗██║██╔══╝
> > ███████╗██║██║ ╚████║███████╗
> > ╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝
> > 
> > 
> > listening on http://127.0.0.1:3000
> > Build cost: 8ms
> > Watching...
> > ```
> 
> This comes from src/server.rs. There was an issue with my merging.

You should remove those lines:
image

**Comment by Bas-Man** [comment]
I have resolved all conflicts and also addressed the Duplicate Banner on Serve.
I actually did the merge from master in to my code again to ensure I had not made any other mistakes.
The Build issue appears to also have in another pull request from @Folyd. So I do not think my code is broken.

**Comment by Bas-Man** [comment]
This code is really complete and ready for review. 

Feedback welcome.

**Comment by Folyd** [comment]
Thanks for working on this. However, this is a huge PR for the reviewer. Would you mind splitting some improvements unrelated to the new article support into another PR? Such as those format changes: 

```diff
entries.push(format!("{}/authors/", base_url));
+entries.push(format!("{base_url}/authors/"));
```

**Comment by Bas-Man** [comment]
I am was doing that. But those PRs didn't get pulled in. So now it's become much larger.
Plus I have had to resolve a number of conflicts that I had been able to avoid. Up until now.

**Comment by Bas-Man** [comment]
> Thanks for working on this. However, this is a huge PR for the reviewer. Would you mind splitting some improvements unrelated to the new article support into another PR? Such as those format changes:
> 
> ```diff
> -entries.push(format!("{}/authors/", base_url));
> +entries.push(format!("{base_url}/authors/"));
> ```

@Folyd Please see draft pr #182 And let me know if this makes things easier to understand.

**Pull request closed without merging**
