### PR TITLE
Required edits to bring new code for --articles into zine and be usable at the cli level

### PR DESCRIPTION
**Pull request by Bas-Man**

### CODE REVIEW

**Comment by Bas-Man** [comment]
- Make the `new_zine_article` functionality available.
- Re-work the logic of Commands::New to use match statement instead of `if` conditionals. Makes the code more maintainable in the future.

**Comment by Folyd** [comment]
Hi, @Bas-Man. Thanks for you splitting PR, however, it is too fragmented for code review. I think a better approach is to split two PR, one is for the new article feature, and one is for another unrelated. What do you think?

**Comment by Bas-Man** [comment]
I know. It was a big set of changes. But it was needed to get it on a path that would be more flexible in the future. 

Let me know which files you want combined. 
'issue.rs', 'article.rs', 'helpers.rs' and 'Cargo.toml' as these go together fairly nicely. 

Then 'author.rs', site.rs'

And finally 'lib.rs', 'new.rs' and 'main.rs'

I have left some things unchanged. As they can be refactored out with small pull requests. 

Thoughts?

**Comment by Bas-Man** [comment]
@Folyd I have update the pull request. Waiting your responses.

**Comment by Bas-Man** [comment]
Pr #183 is the first that needs to be resolved and merged. Then they go in order.

**Pull request closed without merging**
